#!/bin/bash
set -u
cd ~

function compare_files() {
    if [ -f "$2" ]; then

        if ! cmp -s "$1" "$2"; then
          code --diff "$1" "$2"
        fi

    else
        cp -v "$1" "$2"
    fi
}

OS="$(uname -s)"
longOS="$(uname -a)"

if [[ "$OS" == "Linux" ]]; then
  var1="~/.config/nushell/"

  if [[ ! $longOS == *"Microsoft"* ]] && gum confirm "Install wezterm?"; then
    echo "now it will ask for sudo password to install libfuse2 (which is needed for wezterm intallation). Please, enter."
    sudo apt install libfuse2

    brew tap wez/wezterm-linuxbrew
    brew install wezterm
  fi

elif [[ "$OS" == "Darwin" ]]; then
  var1="~/Library/Application Support/nushell/"

  if gum confirm "Install wezterm?"; then
    brew tap wez/wezterm
    brew install --cask wez/wezterm/wezterm
    
    # brew tap homebrew/cask-fonts
    # brew install font-jetbrains-mono-nerd-font  
  fi
else
  echo "Your system ($OS) is unsupported"
  exit 0
fi


if ! type "code" && [[ "$OS" == "Darwin" ]] > /dev/null; then
  if gum confirm "Install vscode?"; then
    echo "Installing VSCode via brew"
    brew install --cask visual-studio-code
  fi
fi

var1=$(eval echo "$var1")

# check if the directory exists
if [ -d ~/cy/ ]; then
  cd ~/cy/
  git stash
  git pull
  git stash pop
else
  mkdir ~/cy/
  git clone https://github.com/cyber-prophet/cy ~/cy/
fi

if [ ! -e "$var1" ]; then
  mkdir -p "$var1"
fi

compare_files ~/cy/kickstart/config.nu "$var1/config.nu"
compare_files ~/cy/kickstart/env.nu "$var1/env.nu"   
compare_files ~/cy/kickstart/wezterm.lua ~/.wezterm.lua   

if [ ! -f ~/.ipfs ]; then
  ipfs init
fi

brew services start ipfs

# to ensure, that bin files of homebrew are in the path of nushell

# nu ~/cy/kickstart/setup-cy.nu 

echo "Cy is installed. Type nu in your terminal, and it will start with cy."
