#!/bin/bash
set -u
cd ~

# check if the directory exists
if [ -d ~/cy/ ]; then
  cd ~/cy/
  git stash
  git pull
  git stash pop
else
  mkdir ~/cy/
  git clone https://github.com/cyber-prophet/cy ~/cy/
fi

nu --execute 'source ~/cy/kickstart/setup-cy.nu'

echo "Cy💎 nushell module and essetial apps are installed. 
Type nu in your terminal, and it will start with cy."

nu
